[build]
  command = "npm run build"
  publish = ".next"
  functions = "./functions"

# nextjs plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-image-optim"
[[plugins]]
  package = "netlify-plugin-inline-source"
[[plugins]]
  package = "netlify-plugin-cache-nextjs"
[[plugins]]
  package = "@netlify/plugin-sitemap"
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
    [plugins.inputs]
	  baseUrl = "https://murshidazher.com/"
	  sitemapPath = "/sitemap.xml"
	  providers = [
		"google",
		"bing",
		"yandex"
	  ]

# email plugin
[[plugins]]
  package = "@netlify/plugin-emails"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"


[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[[redirects]]
    from = "/home"
    to = "/"

[[redirects]]
    from = "/now"
    to = "/"

# social
[[redirects]]
    from = "/twitter"
    to = "https://twitter.com/murshidazher"
[[redirects]]
    from = "/github"
    to = "https://github.com/murshidazher"
[[redirects]]
    from = "/linkedin"
    to = "https://linkedin.com/in/murshidazher"
[[redirects]]
    from = "/dribbble"
    to = "https://dribbble.com/murshidazher"
[[redirects]]
    from = "/instagram"
    to = "https://www.instagram.com/murshidazher"
[[redirects]]
    from = "/behance"
    to = "https://www.behance.net/murshidazher"
[[redirects]]
    from = "/medium"
    to = "https://medium.com/@imurshid"

# other
[[redirects]]
    from = "/resume"
    to = "https://read.cv/murshidazher"
