[build]
  command = "npm run build"
  publish = ".next"
  functions = "./functions"

# nextjs plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-image-optim"
[[plugins]]
  package = "netlify-plugin-inline-source"
[[plugins]]
  package = "netlify-plugin-cache-nextjs"
[[plugins]]
  package = "@netlify/plugin-sitemap"
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
    [plugins.inputs]
	  baseUrl = "https://murshidazher.com/"
	  sitemapPath = "/sitemap.xml"
	  providers = [
		"google",
		"bing",
		"yandex"
	  ]

# email plugin
[[plugins]]
  package = "@netlify/plugin-emails"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"
